### ISSUE TITLE
System.NullReferenceException when trying to protect .NET Core 3.0 WPF application

### ISSUE THREAD

**Issue by alexalok** [mkaring/ConfuserEx#104]
Hello and thank you for keeping up the good work!

I would like to report the issue I've encountered when trying to protect .NET Core 3.0 WPF application. The stacktrace is as follows:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Antlr4.Runtime.AntlrInputStream..ctor(String input)
   at Confuser.Core.ObfAttrParser.TryParse(IReadOnlyDictionary`2 items, String str, ILogger logger) in C:\projects\confuserex\Confuser.Core\ObfAttrParser.cs:line 14
   at Confuser.Core.ObfAttrMarker.ToInfo(IConfuserContext context, ObfuscationAttributeInfo attr, ProtectionSettingsInfo& info) in C:\projects\confuserex\Confuser.Core\ObfAttrMarker.cs:line 148
   at Confuser.Core.ObfAttrMarker.<ReadInfos>d__8.MoveNext() in C:\projects\confuserex\Confuser.Core\ObfAttrMarker.cs:line 204
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at Confuser.Core.ObfAttrMarker.ProtectionSettingsStack.Apply(IDnlibDef target, IEnumerable`1 infos) in C:\projects\confuserex\Confuser.Core\ObfAttrMarker_ProtectionSettingsStack.cs:line 68
   at Confuser.Core.ObfAttrMarker.ProcessTypeMembers(TypeDef type, ProtectionSettingsStack stack, IConfuserContext context, ILogger logger) in C:\projects\confuserex\Confuser.Core\ObfAttrMarker.cs:line 394
   at Confuser.Core.ObfAttrMarker.ProcessModule(ModuleDef module, ProtectionSettingsStack stack, IConfuserContext context, ILogger logger) in C:\projects\confuserex\Confuser.Core\ObfAttrMarker.cs:line 389
   at Confuser.Core.ObfAttrMarker.MarkModule(IConfuserContext context, ConfuserProject project, ProjectModule projModule, ModuleDefMD module, Dictionary`2 rules, Boolean isMain, ILogger logger, ICollection`1 extModules, IPacker& packer, IDictionary`2& packerParams) in C:\projects\confuserex\Confuser.Core\ObfAttrMarker.cs:line 382
   at Confuser.Core.ObfAttrMarker.MarkProject(ConfuserProject proj, ConfuserContext context, CancellationToken token) in C:\projects\confuserex\Confuser.Core\ObfAttrMarker.cs:line 227
   at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in C:\projects\confuserex\Confuser.Core\ConfuserEngine.cs:line 202
```

I am using the latest ConfuserEx's version at the time - `Confuser.Core 2.0.0-alpha+02bc8fb6b5`.

Should you need any additional information, please feel free to request it and I will try my best to do so.

**Comment by alexalok** [comment]
I would also like to add that using MSBuild with `Confuser.MSBuild 1.3.1` on the same project results in 

```
1>Failed to resolve a type, check if all dependencies are present in the correct version.
1>Could not resolve type: System.Runtime.CompilerServices.IAsyncStateMachine (System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
```

I have tried adding 

```
<module path="C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0\System.Runtime.dll" external="true" />
```

to `.crpoj` but the same error still persists.
