### ISSUE TITLE
Error occurred while using invalid metadata protection.

### ISSUE THREAD

**Issue by icortana** [mkaring/ConfuserEx#13]
`[DEBUG] Encrypting resources...
[ERROR] Unknown error occurred.
Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at dnlib.DotNet.Writer.MDTable`1.get_Item(UInt32 rid)
   at Confuser.Core.Services.RandomGenerator.Shuffle[T](MDTable`1 table)
   at Confuser.Protections.InvalidMetadataProtection.InvalidMDPhase.Randomize[T](MDTable`1 table)
   at Confuser.Protections.InvalidMetadataProtection.InvalidMDPhase.OnWriterEvent(Object sender, ModuleWriterEventArgs e)
   at dnlib.DotNet.Writer.EventHandler2`1.Invoke(Object sender, TEventArgs e)
   at dnlib.DotNet.Writer.ModuleWriterOptionsBase.RaiseEvent(Object sender, ModuleWriterEventArgs e)
   at dnlib.DotNet.Writer.ModuleWriterBase.OnWriterEvent(ModuleWriterEvent evt)
   at dnlib.DotNet.Writer.ModuleWriterBase.Metadata_MetadataEvent(Object sender, MetadataWriterEventArgs e)
   at dnlib.DotNet.Writer.Metadata.OnMetadataEvent(MetadataEvent evt)
   at dnlib.DotNet.Writer.Metadata.Create()
   at dnlib.DotNet.Writer.Metadata.CreateTables()
   at dnlib.DotNet.Writer.ModuleWriter.WriteImpl()
   at dnlib.DotNet.Writer.ModuleWriterBase.Write(Stream dest)
   at dnlib.DotNet.ModuleDef.Write(Stream dest, ModuleWriterOptions options)
   at Confuser.Core.ConfuserEngine.WriteModule(ConfuserContext context)
   at Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContext context)
   at Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context)
   at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token)
Failed at 2:04 PM, 0:08 elapsed.

`

Location : ConfuserEx\Confuser.Core\Services\RandomService.cs Line 208
Solution : 
![image](https://user-images.githubusercontent.com/25761337/50039794-78d56200-0073-11e9-86d4-fbe8d335212a.png)

**Comment by mkaring** [comment]
Thank you for reporting the issue.
Could you please verify that this build is now working for you:

https://ci.appveyor.com/project/mkaring/confuserex/builds/21044540/artifacts

**Comment by icortana** [comment]
Thanks, it's working now.
