### ISSUE TITLE
Could not resolve type: System.Runtime.CompilerServices.IAsyncStateMachine

### ISSUE THREAD

**Issue by mc0re** [mkaring/ConfuserEx#142]
Confuser complains about `System.Runtime.CompilerServices.IAsyncStateMachine`. This interface is located in `System.Runtime.CompilerServices`, which itself seems to be a part of `.NET Core App` framework package. Used in `async`/`await` tuple.

I use "Publish" feature of Visual Studio to dump all the DLLs into a directory. It is a self-contained deployment, so it contains all the DLLs the application should need. Then I'm trying to obfuscate only the DLLs my project produced, not Microsoft ones :-)  It's a *.NET Core 3.1* project with *.NET Standard 2.1* libraries.

Is there something I am missing in the setup?

Log:
```
[DEBUG] Building VTables & identifier list...
[ERROR] Failed to resolve a type, check if all dependencies are present in the correct version.
Exception: dnlib.DotNet.TypeResolveException: Could not resolve type: System.Runtime.CompilerServices.IAsyncStateMachine (netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51)
   at dnlib.DotNet.TypeRef.ResolveThrow(ModuleDef sourceModule)
   at Confuser.Renamer.VTableStorage.GetVTable(ITypeDefOrRef type)
   at Confuser.Renamer.VTable.ConstructVTable(TypeDef typeDef, VTableStorage storage)
   at Confuser.Renamer.VTableStorage.GetOrConstruct(TypeDef type)
   at Confuser.Renamer.VTableStorage.GetVTable(ITypeDefOrRef type)
   at Confuser.Renamer.AnalyzePhase.Execute(ConfuserContext context, ProtectionParameters parameters)
   at Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContext context)
   at Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context)
   at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token)
[ERROR] ---BEGIN DEBUG INFO---
[ERROR] Installed Framework Versions:
[ERROR]     v2.0.50727  2.0.50727.4927
[ERROR]     v3.0  3.0.30729.4926
[ERROR]     v3.5  3.5.30729.4926
[ERROR]     v4
[ERROR]     Client  4.8.04084
[ERROR]     Full  4.8.04084
[ERROR]     v4.0
[ERROR]     Client  4.0.0.0
[ERROR]     v4.5 528372
[ERROR]
[ERROR] Cached assemblies:
...
```

**Comment by KvanTTT** [comment]
It's the known issue, see #106

**Comment by mc0re** [comment]
It'd be nice to mention in the feature list, that Core is not supported, so people don't waste time trying to integrate Confuser into the pipeline...
