### ISSUE TITLE
The rename argument renPdb=true causes a null pointer

### ISSUE THREAD

**Issue by griknok** [mkaring/ConfuserEx#182]
Confuser 1.4.1 with .NET 4.7.2 Winforms exe
Create a project with only the default rename mode (unicode) and renPdb=true:
`<protection id="rename">
  <argument name="mode" value="unicode" />
  <argument name="renPdb" value="true" />
</protection>`

Run it and get:
`[DEBUG] Renaming...
[ERROR] Unknown error occurred.
Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Confuser.Renamer.RenamePhase.Execute(ConfuserContext context, ProtectionParameters parameters)
   at Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContext context)
   at Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context)
   at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token)
Failed at 1:27 PM, 0:00 elapsed.`

**Comment by mkaring** [comment]
I only found a single reason on first glance that could cause this issue.
It's fixed in [this build][1]. Could you test this build and see if this resolves the issue for you?

[1]: https://ci.appveyor.com/project/mkaring/confuserex/builds/34551410/artifacts

**Comment by griknok** [comment]
Yep! Fixed
