### ISSUE TITLE
ConfusedEx 2/ v1.4.1 & can't run my exe after using v1.4.1

### ISSUE THREAD

**Issue by MrGonzy** [mkaring/ConfuserEx#241]
Hello, im confused. The page says ConfusedEx 2 but the latest build is v1.4.1 ? How can i get the v2.0? I tried downloading the source code and try building it but says i cant because **i have no priviledge and some kind of paket.exe error.** I am currently using v1.4.1 and discover that my **.exe** was unable to run. Mouse cursor was loading and it was like trying to start up but nothing is showing. 

My project is using .NET Framework 4.7.2, c++ winform CL, release version. It worked in v1.0.0 but after knowing that there is an unpacking available from youtube, i decided to try v1.4.1 but came into a problem. Can any one assist me ? Thank you

**Comment by MrGonzy** [comment]
Update - this is the error printed out 


```

> Unhandled Exception: System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'htvVBnLaDuXqFJITBmnMYUeRtdfq, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Attempt to load an unverifiable executable with fixups (IAT with more than 2 sections or a TLS section.) (Exception from HRESULT: 0x80131019) ---> System.IO.FileLoadException: Attempt to load an unverifiable executable with fixups (IAT with more than 2 sections or a TLS section.) (Exception from HRESULT: 0x80131019)
>    --- End of inner exception stack trace ---
>    at System.Reflection.RuntimeAssembly.nLoadImage(Byte[] rawAssembly, Byte[] rawSymbolStore, Evidence evidence, StackCrawlMark& stackMark, Boolean fIntrospection, Boolean fSkipIntegrityCheck, SecurityContextSource securityContextSource)
>    at System.Reflection.Assembly.Load(Byte[] rawAssembly)
>    at ?????????????????????????????????????????()
>    at .cctor()
>    --- End of inner exception stack trace ---
> 

```
