### ISSUE TITLE
Skip all the obfuscation of a class

### ISSUE THREAD

**Issue by kassnd** [mkaring/ConfuserEx#283]
Hi
i tried use this to exclude a entire namespace from being obfuscate, but it's don't work

the namespace before:
```
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

[assembly: System.Reflection.Obfuscation(Exclude = false, Feature = "namespace('Test'):preset(none);-anti debug;-anti dump;-anti ildasm;-anti tamper;-constants;-harden;-invalid metadata;-typescramble;-rename")]

namespace Test
{ 
     static class Program
     {
        static void Test()
        {
            MessageBox.Show("Hello, World!");
        }
     }
}
```

After:
```
using System;
using System.Windows.Forms;

namespace Test
{
	// Token: 0x0200000E RID: 14
	internal static class Program
	{
		// Token: 0x06000040 RID: 64 RVA: 0x000082C4 File Offset: 0x000066C4
		private static void Test()
		{
			Program.\u206F\u202C\u202B\u200C\u200E\u206A\u202D\u202C\u206B\u200E\u200D\u200C\u202E\u206B\u206D\u202C\u206A\u206B\u200E\u202C\u200F\u206F\u206D\u202D\u206C\u200E\u200C\u206A\u2029\u202D\u206C\u206D\u202D\u2029\u206C\u202A\u202C\u202A\u202C\u206F\u202C\u202B\u200C\u200E\u206A\u202D\u202C\u206B\u200E\u200D\u200C\u202E\u206B\u206D\u202C\u206A\u206B\u200E\u202C\u200F\u206F\u206D\u202D\u206C\u200E\u200C\u206A\u2029\u202D\u206C\u206D\u202D\u2029\u206C\u202A\u202C\u202A("Hello, World!");
		}

		// Token: 0x06000041 RID: 65 RVA: 0x00005EE0 File Offset: 0x000042E0
		static DialogResult \u206F\u202C\u202B\u200C\u200E\u206A\u202D\u202C\u206B\u200E\u200D\u200C\u202E\u206B\u206D\u202C\u206A\u206B\u200E\u202C\u200F\u206F\u206D\u202D\u206C\u200E\u200C\u206A\u2029\u202D\u206C\u206D\u202D\u2029\u206C\u202A\u202C\u202A\u202C\u206F\u202C\u202B\u200C\u200E\u206A\u202D\u202C\u206B\u200E\u200D\u200C\u202E\u206B\u206D\u202C\u206A\u206B\u200E\u202C\u200F\u206F\u206D\u202D\u206C\u200E\u200C\u206A\u2029\u202D\u206C\u206D\u202D\u2029\u206C\u202A\u202C\u202A(string)
		{
			/*
An exception occurred when decompiling this method (06000041)

ICSharpCode.Decompiler.DecompilerException: Error decompiling System.Windows.Forms.DialogResult Test.Program::⁯‬‫‌‎⁪‭‬⁫‎‍‌‮⁫⁭‬⁪⁫‎‬‏⁯⁭‭⁬‎‌⁪ ‭⁬⁭‭ ⁬‪‬‪\u202C⁯‬‫‌‎⁪‭‬⁫‎‍‌‮⁫⁭‬⁪⁫‎‬‏⁯⁭‭⁬‎‌⁪ ‭⁬⁭‭ ⁬‪‬‪(System.String)

 ---> System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'length')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
   at ICSharpCode.Decompiler.ILAst.ILAstBuilder.StackSlot.ModifyStack(StackSlot[] stack, Int32 popCount, Int32 pushCount, ByteCode pushDefinition) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstBuilder.cs:line 48
   at ICSharpCode.Decompiler.ILAst.ILAstBuilder.StackAnalysis(MethodDef methodDef) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstBuilder.cs:line 387
   at ICSharpCode.Decompiler.ILAst.ILAstBuilder.Build(MethodDef methodDef, Boolean optimize, DecompilerContext context) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstBuilder.cs:line 269
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters, MethodDebugInfoBuilder& builder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 112
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 88
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 92
   at ICSharpCode.Decompiler.Ast.AstBuilder.<>c__DisplayClass90_0.<AddMethodBody>b__0() in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 1519
*/;
		}
	}
}

```

can someone help me with this? thx

**Comment by mkaring** [comment]
You did not disable the [`ref proxy`](https://github.com/mkaring/ConfuserEx/wiki/Reference-Proxy-Protection) protection. That is the one still active here.

**Comment by kassnd** [comment]
> 
> 
> You did not disable the [`ref proxy`](https://github.com/mkaring/ConfuserEx/wiki/Reference-Proxy-Protection) protection. That is the one still active here.

thanks, you do a great job for our community
