### ISSUE TITLE
Unreachable code reached.

### ISSUE THREAD

**Issue by LoghamLogan** [mkaring/ConfuserEx#55]
I'm getting the following error in v1.1.0(released) v1.2.0(released) and v2.0 (built).

> [ERROR] Unknown error occurred.
Exception: Confuser.Core.UnreachableException: Unreachable code reached.
   at Confuser.Renamer.Analyzers.LdtokenEnumAnalyzer.Analyze(ConfuserContext context, INameService service, ProtectionParameters parameters, IDnlibDef def)
   at Confuser.Renamer.AnalyzePhase.Analyze(NameService service, ConfuserContext context, ProtectionParameters parameters, IDnlibDef def, Boolean runAnalyzer)
   at Confuser.Renamer.AnalyzePhase.Execute(ConfuserContext context, ProtectionParameters parameters)
   at Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContext context)
   at Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context)
   at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token)
Failed at 01:26, 0:00 elapsed.

Debugging shows that the instruction operand is equal to null, causing UnreachableException to be thrown.

The instruction in question shows as: ```IL_0032: ldtoken null```

Any advice on what might cause this would be appreciated :)

**Comment by LoghamLogan** [comment]
Update: I cleaned/rebuilt my project, recreated the obfuscation project and everything worked as expected.

**Comment by mkaring** [comment]
Glad I could help. :wink:

**Comment by LoghamLogan** [comment]
For future reference; Looks like it was caused by using a packer (Costura) prior to running it through confuser.
