### ISSUE TITLE
Confuser task does not work

### ISSUE THREAD

**Issue by KvanTTT** [mkaring/ConfuserEx#59]
I'm trying to perform the following steps:

1. Create project **ObfuscationTest.csproj** here: https://github.com/KvanTTT/ObfuscationTest
2. Add **Confuser.MSBuild** dependecy from https://www.nuget.org/packages/Confuser.MSBuild/2.0.0-alpha-0191
3. Add **ObfuscationTest.crproj** file with the following content:

```xml
<project baseDir="bin\Debug\netcoreapp2.1" outputDir="..\..\Obfuscated" >
    <rule pattern="true" inherit="false">
        <protection id="anti ildasm" />
        <protection id="constants" />
        <protection id="invalid metadata" />
        <protection id="rename">
            <argument name="mode" value="decodable" />
        </protection>
    </rule>
    <module path="ObfuscationTest.exe" />
</project>
Add Obfuscation attribute to .csproj file:
<PropertyGroup>
    <Obfuscate>True</Obfuscate>
</PropertyGroup>
```

After that, I'm trying to compile project (Rider) but it's failing with the following error.

```
0>------- Project finished: ObfuscationTest. Succeeded: False. Errors: 0. Warnings: 0
```

Obfuscated assembly is also not being created.

If I run msbuild via command line, the following error occurs:

```
ConfuseAssembly:
  [CRITICAL] An IO error occurred, check if all input/output locations are readable/writable.
```

But all paths are valid and such **.crproj** works fine with Confuser command line tool.

**Comment by Gwindalmir** [comment]
I did the same thing, but with a .NET Standard library, and I just get 
`[CRITICAL] Unknown error occurred.`

[ObfuscatorTest.zip](https://github.com/mkaring/ConfuserEx/files/3503444/ObfuscatorTest.zip)

**Comment by mkaring** [comment]
I'm trying to get a handle on this. I tried it with the 1.3 version of the msbuild project and it seems to work fine.

**Comment by mkaring** [comment]
@KvanTTT Have you tried this using the 1.3.1 Version that is deployed to Nuget.org? It works for me using it.

**Comment by KvanTTT** [comment]
Yes, now it works. But there are couple of notes:

* If I remove `baseDir` or `outputDir` from `.crproj` file, the task does not work. It breaks with the following exception:

```
  Confuser.MSBuild.targets(46, 5): [MSB4018] The "Confuser.MSBuild.Tasks.CreateProjectTask" task failed unexpectedly.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Confuser.Core.Project.ConfuserProject.Load(XmlDocument doc) in C:\projects\confuserex\Confuser.Core\Project\ConfuserProject.cs:line 551
   at Confuser.MSBuild.Tasks.CreateProjectTask.Execute() in C:\projects\confuserex\Confuser.MSBuild.Tasks\CreateProjectTask.cs:line 31
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

Even if I define `ConfuserOutDir` in `.csproj` file, that exception is being thrown.

* Task does not work if I change the target from `net472` to `netcoreapp2.1` with unexpected errors:

```
Confuser.MSBuild.targets(66, 5): Cannot find protection with ID 'anti ildasm'.
```

**Comment by kinosang** [comment]
got `Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'` on .Net Core 3.1 with .NetStandard 2.1 project.

**Comment by mkaring** [comment]
@kinosang Are you building with `dotnet build` or `msbuild`? Only the latter is currently supported as the runtime of ConfuserEx is currently not working using .NET Core.

The error message regarding `Microsoft.Extensions.Logging.Abstractions` can usually be fixed by adding that assembly explicitly to the `*.crproj` file as external reference.

**Comment by kinosang** [comment]
@mkaring I'm using `dotnet build`, I'll try with `msbuild`.
