### ISSUE TITLE
MemberRefResolveException

### ISSUE THREAD

**Issue by eaba** [mkaring/ConfuserEx#71]
I have been facing this issue since yesterday using 2.0:
````
Failed to resolve a member, check if all dependencies are present in the correct version.
dnlib.DotNet.MemberRefResolveException: Could not resolve method: System.Collections.Generic.IEnumerable`1<System.Collections.Generic.Dictionary`2<System.String,System.String>> ?????????????????????????????????????????`1<?????????????????????????????????????????>::?????????????????????????????????????????(?????????????????????????????????????????) (Repository, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)
   at dnlib.DotNet.MemberRef.ResolveMethodThrow()
   at Confuser.Renamer.VTable.ConstructVTable(TypeDef typeDef, VTableStorage storage) in C:\projects\confuserex\Confuser.Renamer\VTable.cs:line 224
   at Confuser.Renamer.VTableStorage.GetOrConstruct(TypeDef type) in C:\projects\confuserex\Confuser.Renamer\VTable.cs:line 378
   at Confuser.Renamer.AnalyzePhase.Confuser.Core.IProtectionPhase.Execute(IConfuserContext context, IProtectionParameters parameters, CancellationToken token) in C:\projects\confuserex\Confuser.Renamer\AnalyzePhase.cs:line 52
   at Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`2 func, Func`1 targets, ConfuserContext context, CancellationToken token) in C:\projects\confuserex\Confuser.Core\Pr
````

Tried removing `rename` with no effect. Current project is:
````
<project outputDir=".\Confused" baseDir="." xmlns="http://confuser.codeplex.com">
  <rule pattern="true" preset="normal" inherit="true">
    <protection id="anti debug" action="remove"/>
    <protection id="resources" action="remove"/>
    <protection id="ctrl flow" action="remove"/>
    <protection id="ref proxy" action="remove"/>
	<protection id="rename" action="remove"/>
	<protection id="constants" action="remove"/>
	<protection id="anti tamper" action="remove"/>
	<protection id="anti dump" action="remove"/>
	<protection id="anti ildasm" action="remove"/>
	<protection id="invalid metadata" action="remove"/>
  </rule>
  <module path="Repository.dll"/>
  <module path="dd.dll" />
  <module path="d.dll" />
  <module path="r.dll"/>
  <module path="xxxx.dll"/>
  <probePath>C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All\2.1.1</probePath>
  <probePath>C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\2.1.1</probePath>
  <probePath>C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.1</probePath>
  <probePath>xxxxxx\ddddd</probePath>
</project>
````

**Comment by eaba** [comment]
So this issue was my own error. I was trying, unknowingly, to obfuscate a .dll already obfuscated!!
