### ISSUE TITLE
Exception was Thrown

### ISSUE THREAD

**Issue by wmjordan** [mkaring/ConfuserEx#96]
I was using the latest built artifacts on appveyor.

No error was encountered if I rolled back to release 1.3.

Here's the stack trace:
````
  System.ArgumentException: An item with the same key has already been added.
     at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
     at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
     at Confuser.Core.ObfAttrParser.ObfProtectionAttrParser.VisitItem(ItemContext context) in C:\projects\confuserex\Confuser.Core\ObfAttrParser.cs:line 130
     at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.VisitChildren(IRuleNode node)
     at Confuser.Core.ObfAttrParser.ParseProtection(IReadOnlyDictionary`2 items, IDictionary`2 settings, String str, ILogger logger) in C:\projects\confuserex\Confuser.Core\ObfAttrParser.cs:line 35
     at Confuser.Core.ObfAttrMarker.ProtectionSettingsStack.ApplyInfo(IReadOnlyDictionary`2 protections, IDnlibDef context, ProtectionSettings settings, IEnumerable`1 infos, ApplyInfoType type, ILogger logger) in C:\projects\confuserex\Confuser.Core\ObfAttrMarker_ProtectionSettingsStack.cs:line 103
     at Confuser.Core.ObfAttrMarker.ProtectionSettingsStack.Apply(IDnlibDef target, IEnumerable`1 infos) in C:\projects\confuserex\Confuser.Core\ObfAttrMarker_ProtectionSettingsStack.cs:line 75
     at Confuser.Core.ObfAttrMarker.ProcessMember(PropertyDef property, ProtectionSettingsStack stack, IConfuserContext context, ILogger logger) in C:\projects\confuserex\Confuser.Core\ObfAttrMarker.cs:line 414
     at Confuser.Core.ObfAttrMarker.ProcessTypeMembers(TypeDef type, ProtectionSettingsStack stack, IConfuserContext context, ILogger logger) in C:\projects\confuserex\Confuser.Core\ObfAttrMarker.cs:line 396
     at Confuser.Core.ObfAttrMarker.ProcessModule(ModuleDef module, ProtectionSettingsStack stack, IConfuserContext context, ILogger logger) in C:\projects\confuserex\Confuser.Core\ObfAttrMarker.cs:line 386
     at Confuser.Core.ObfAttrMarker.MarkModule(IConfuserContext context, ConfuserProject project, ProjectModule projModule, ModuleDefMD module, Dictionary`2 rules, Boolean isMain, ILogger logger, ICollection`1 extModules, IPacker& packer, IDictionary`2& packerParams) in C:\projects\confuserex\Confuser.Core\ObfAttrMarker.cs:line 380
     at Confuser.Core.ObfAttrMarker.MarkProject(ConfuserProject proj, ConfuserContext context, CancellationToken token) in C:\projects\confuserex\Confuser.Core\ObfAttrMarker.cs:line 225
     at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in C:\projects\confuserex\Confuser.Core\ConfuserEngine.cs:line 202
````

**Comment by mkaring** [comment]
What branch is that build from? It looks like a build from the `release/2.0` branch. Is that correct?

**Comment by wmjordan** [comment]
Yep. release/2.0.

**Comment by wmjordan** [comment]
I no longer met with this any more.
It should have been fixed, I guess.
